export { ReactComponent as IDeadlift } from 'assets/svg/deadlift.svg'
export { ReactComponent as IPress } from './press.svg'
export { ReactComponent as ISquat } from './squat.svg'
export { ReactComponent as IBanch } from './banch_press.svg'
export { ReactComponent as ICalendar } from './calendar.svg'
